# Generated by Django 5.1.3 on 2025-04-03 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("nacionalidade", models.CharField(max_length=50)),
                ("ano_inicio", models.IntegerField()),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="artistas_fotos/"
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("ano_lancamento", models.IntegerField()),
                (
                    "capa",
                    models.ImageField(blank=True, null=True, upload_to="capas_albuns/"),
                ),
                (
                    "artista",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albuns",
                        to="artistas.artista",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Musica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("duracao", models.DurationField()),
                ("letra", models.TextField(blank=True, null=True)),
                ("link_streaming", models.URLField(blank=True, null=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musicas",
                        to="artistas.album",
                    ),
                ),
            ],
        ),
    ]
