# Generated by Django 5.1.3 on 2025-04-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artistas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="ficheiro",
            field=models.FileField(
                blank=True, null=True, upload_to="artistas/ficheiros"
            ),
        ),
        migrations.AddField(
            model_name="artista",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="artistas/fotos"),
        ),
    ]
