# Generated by Django 5.1.3 on 2025-04-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artistas", "0002_artista_ficheiro_artista_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artista",
            name="ficheiro",
            field=models.FileField(blank=True, null=True, upload_to="app/ficheiros"),
        ),
        migrations.AlterField(
            model_name="artista",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="app/fotos"),
        ),
    ]
