# Generated by Django 5.1.3 on 2025-04-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artistas", "0003_alter_artista_ficheiro_alter_artista_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artista",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="artistas/"),
        ),
    ]
