# Generated by Django 5.2.1 on 2025-06-03 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("docentes", models.CharField(max_length=300)),
                ("link_moodle", models.URLField()),
                ("link_ulusofona", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("disciplina", models.CharField(max_length=100)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="prof_pic"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("logo", models.ImageField(upload_to="tecnologias_logos/")),
            ],
        ),
        migrations.CreateModel(
            name="Visitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("data_visita", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("link_github", models.URLField(blank=True, null=True)),
                ("link_demo", models.URLField(blank=True, null=True)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.disciplina",
                    ),
                ),
                ("tecnologias", models.ManyToManyField(to="portfolio.tecnologia")),
            ],
        ),
        migrations.CreateModel(
            name="ImagemProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="projetos_imagens/")),
                ("descricao", models.CharField(blank=True, max_length=255)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="portfolio.projeto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conceito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conceitos_aplicados", models.TextField()),
                ("desafios_tecnicos", models.TextField()),
                (
                    "projeto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.projeto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "disciplinas",
                    models.ManyToManyField(blank=True, to="portfolio.disciplina"),
                ),
                (
                    "projetos",
                    models.ManyToManyField(blank=True, to="portfolio.projeto"),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
            ],
        ),
    ]
