# Generated by Django 5.1.3 on 2025-04-17 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="conceito_aplicado",
        ),
        migrations.RenameField(
            model_name="disciplina",
            old_name="link_web_ofc",
            new_name="link_ulusofona",
        ),
        migrations.RenameField(
            model_name="projeto",
            old_name="link_video_demo",
            new_name="link_demo",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="aspetos_tecnicos",
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="docentes",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="imagemprojeto",
            name="imagem",
            field=models.ImageField(upload_to="projetos_imagens/"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="logo",
            field=models.ImageField(upload_to="tecnologias_logos/"),
        ),
        migrations.CreateModel(
            name="Conceito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conceitos_aplicados", models.TextField()),
                ("desafios_tecnicos", models.TextField()),
                (
                    "projeto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.projeto",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ConceitoAplicado",
        ),
    ]
