# Generated by Django 5.1.3 on 2025-05-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_professor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interesses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(blank=True, max_length=250)),
                ("disciplina", models.ManyToManyField(to="portfolio.disciplina")),
                ("projeto", models.ManyToManyField(to="portfolio.projeto")),
                ("tecnologias", models.ManyToManyField(to="portfolio.tecnologia")),
            ],
        ),
    ]
