# Generated by Django 5.1.3 on 2025-05-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_interesses"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Interesses",
            new_name="Interesse",
        ),
    ]
