# Generated by Django 5.1.3 on 2025-05-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_rename_interesses_interesse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interesse",
            name="disciplina",
        ),
        migrations.RemoveField(
            model_name="interesse",
            name="projeto",
        ),
        migrations.AddField(
            model_name="interesse",
            name="disciplinas",
            field=models.ManyToManyField(blank=True, to="portfolio.disciplina"),
        ),
        migrations.AddField(
            model_name="interesse",
            name="projetos",
            field=models.ManyToManyField(blank=True, to="portfolio.projeto"),
        ),
        migrations.AlterField(
            model_name="interesse",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="interesse",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
    ]
