# Generated by Django 5.1.3 on 2025-04-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "artigos",
            "0002_artigo_data_publicacao_alter_artigo_autor_comentario_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="artigo",
            name="data_publicacao",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
