# Generated by Django 5.1.3 on 2025-05-15 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0003_alter_artigo_data_publicacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="artigo",
            name="rating",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
