# Generated by Django 5.1.3 on 2025-05-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0004_artigo_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artigo",
            name="rating",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
