# Generated by Django 5.1.3 on 2025-05-20 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0005_alter_artigo_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comentario",
            old_name="texto",
            new_name="conteudo",
        ),
        migrations.RenameField(
            model_name="comentario",
            old_name="data",
            new_name="data_comentario",
        ),
        migrations.RenameField(
            model_name="comentario",
            old_name="autor",
            new_name="nome",
        ),
        migrations.AlterField(
            model_name="artigo",
            name="data_publicacao",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
