# Generated by Django 5.1.3 on 2025-05-20 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0006_rename_texto_comentario_conteudo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rate",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rating",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("artigo", "usuario")},
        ),
    ]
